### ISSUE TITLE
401 response with check_version

### ISSUE THREAD

**Issue by jri-sp** [timdaman/check_docker#27] opened 2018-03-01 12:23 UTC
Hi,

It seems that `--check_version ` command fails when you have non-official containers.

For example, I use those images:
```
docker.elastic.co/elasticsearch/elasticsearch:6.0.0
redis:4
```

It fail with Elasticsearch and works with Redis.
It also fail with images that I made and published on Docker Hub.

The URL to get a token is:
`https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/docker.elastic.co/elasticsearch/elasticsearch:pull`
This request is working great, but not this one:
`https://index.docker.io/v2/library/docker.elastic.co/elasticsearch/elasticsearch/manifests/6.0.0`
The query fails with 401 error status, so unauthorized. 

Any idea ?

**Comment by timdaman** [comment] 2018-03-05 05:30
Yeah, that feature was marked experimental because it is a fair bit of work to implement correctly and I didn't want to let that hold up releasing the whole program. I know why it is happening and spent some time this weekend on it but I never got it done. I still working on it but it may be some time, maybe a week or two.

**Comment by timdaman** [comment] 2018-03-08 06:25
I think I have something that will work for you. Check out my 'prep_for_v2' branch. 
https://github.com/timdaman/check_docker/tree/prep_for_v2
I still have a bit of work left to do on this branch but I would really appreciate your feedback before I merge to master.

**Comment by jri-sp** [comment] 2018-03-08 09:03
Hi @timdaman ! Thanks a lot for your answer!

Unfortunately, it's not working for me. :( 
I've a timeout issue. Here is my output (I've added a print for the `url` variable if it can help):
```
# ./check_docker --version
URL=http://docker.elastic.co/v2/elasticsearch/elasticsearch/manifests/6.0.0
Traceback (most recent call last):
  File "/usr/lib64/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib64/python3.4/http/client.py", line 871, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python3.4/socket.py", line 516, in create_connection
    raise err
  File "/usr/lib64/python3.4/socket.py", line 507, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./check_docker", line 665, in perform_checks
    check_version(container)
  File "./check_docker", line 422, in check_version
    reg_info = head_url(url=url)
  File "/usr/lib64/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "./check_docker", line 200, in head_url
    response = better_urllib_head.open(url, timeout=timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib64/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 1211, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
UNKNOWN: Exception raised during check: URLError(timeout('timed out',),)
```

I'm using Python 3.4.5.

Don't hesitate if I can help! :)

**Comment by timdaman** [comment] 2018-03-09 03:13
Thanks for testing it. Turns out I disabled TLS on my personal registry. I switched the check to use TLS by default and added support for indicating insecure registries.

I think this should fix it for you. Could you please give it another try.

**Comment by jri-sp** [comment] 2018-03-09 14:10
Hi @timdaman !

thanks again for your quick fix!

Well, currently it's not totally working :)

It's ok for http://docker.elastic.co/v2/elasticsearch/elasticsearch/manifests/6.0.0 but not with redis image from official Docker library. \o/

The `image_url` value in this case is : `redis:4` and it doesn't match with the regex in `full_re`.
The problem comes from the image tag regex.
My suggestion is to replace  `image_tag_re` with this: `(?P<image_tag>[a-zA-Z0-9_.-]+)`
I don't know for which case the first `[a-zA-Z0-9]` is... do you know ?

What do you think of this fix ?


BTW, here my trace without my regex change:
```
Traceback (most recent call last):
  File "./check_docker", line 681, in perform_checks
    check_version(container, args.insecure_registries)
  File "./check_docker", line 413, in check_version
    registry = image_parsed.group('registry') if image_parsed.group('registry') else DEFAULT_PUBLIC_REGISTRY
AttributeError: 'NoneType' object has no attribute 'group'
UNKNOWN: Exception raised during check of 'redis_dev': AttributeError("'NoneType' object has no attribute 'group'",)
```

**Comment by timdaman** [comment] 2018-03-09 15:31
The Docker documentation says 

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

The first grouping ensure the tag starts with a valid letter. The problem is the second grouping should not be modified by a '+', it should be modified by a '*'. That way single letter tags can be supported.
I just pushed that tweak.

Your fix works but has the side effect of ignoring the spec. The spec is actually pretty complex so I have a couple edge case too; I don't handle '__' specially in image names and I can't handle registry hostnames that don't contain '.'. I plan on fixing those once I have all the previously known issues resolved.

**Comment by jri-sp** [comment] 2018-03-09 18:31
Thanks @timdaman !
With your last fix it works with all containers in my stack now :)

I agree with you, it's better to follow the spec rather than my fix.
Thanks again for your time on this !

**Comment by timdaman** [comment] 2018-03-18 05:30
I have another update. When I added in the unit tests for the updated version checks I discovered few bugs which I think should be fixed now.

**Comment by timdaman** [comment] 2018-03-19 03:37
FYI, I just merged v2.0.0 into master. I am going to wait a day before pushing to pypi to give bugs a chance to bubble up.
Thank you for bring up the issue and testing the solution. If you notice anything broken master please let me know.

**Comment by jri-sp** [comment] 2018-03-19 07:55
Hi! 

Thanks a lot! I've pulled it on my server and it check about 10 containers from various registries for now without problem. 
I think this issue is solved :)

**Comment by timdaman** [comment] 2018-03-20 01:00
Sweet. I am closing this issue as I have pushed the update to pypi.

**Closed by timdaman** 2018-03-20 01:00 UTC
