### ISSUE TITLE
multiple container names cannot be found

### ISSUE THREAD

**Issue by sadai-gh** [timdaman/check_docker#31] opened 2018-03-19 10:01 UTC
Hi,

it seems that containers with multiple names cannot be found but only the first one, I tried it with several regex but no look.
Would be nice if I could query the name of the container which is displayed in 'docker ps'.

I appreciate your work on this.

**Comment by timdaman** [comment] 2018-03-19 14:21
I am glad the plugin is helpful. Could you send me a sample of you are using the command? For example

    ./check_docker --memory 50:70:% --containers 'dashboard_.*'

Without that info I have to guess what the issue may be. Are you omitting the quotes around the regular expression?

**Comment by sadai-gh** [comment] 2018-03-19 15:11
With the following command I get the name(s) for one of the containers:

`docker ps -a --no-trunc --format "{{.Names}}"`

`hylotox/mysql,mantis-test/mysql,mantis/mysql,mariadb,vtiger/mysql`

'docker ps' just lists this container as 'mariadb' (real name), but with that name the container is not found, same with any regex.

Thanks for you help, please let me know if you need more input to reproduce.

**Comment by timdaman** [comment] 2018-03-19 18:00
Huh, wow. I have never seen a container with more than one name. How did you do that?

I will take a peek tonight on how I can support that.

**Comment by sadai-gh** [comment] 2018-03-20 13:41
I think this comes from linking (--link) containers together, hope this is not too hard to solve?

**Comment by timdaman** [comment] 2018-03-21 03:02
Ah ha, I see now. I have actually never used linking because it has been deprecated since I started with Docker. There id a warning saying they may yank support for it. 
https://docs.docker.com/compose/compose-file/#links
I suppose they have been warning for years now(ugh) so they are unlikely to abandon it anytime soon.

I have a few ideas of how to address it but I want to make sure that the alerts make sense. Basically that means the alerts should always use the same name that is shown with `docker ps` when reporting stats.

**Comment by timdaman** [comment] 2018-03-21 03:20
Ah ha, I think I figured it out. Could you try this one and see if it fixes your issue.
https://raw.githubusercontent.com/timdaman/check_docker/multi-names/check_docker

**Comment by sadai-gh** [comment] 2018-03-21 08:42
Thank you for your work on that, unfortunately I get a socket timeout:

./check_docker_multi --containers mariadb --cpu 50:80
Traceback (most recent call last):
  File "./check_docker_multi", line 766, in perform_checks
    containers = get_containers(args.containers, args.present)
  File "./check_docker_multi", line 261, in get_containers
    all_container_names = set(get_container_info(id)['Name'][1:] for id in all_container_ids)
  File "./check_docker_multi", line 261, in <genexpr>
    all_container_names = set(get_container_info(id)['Name'][1:] for id in all_container_ids)
  File "./check_docker_multi", line 227, in get_container_info
    content, _ = get_url(daemon + '/containers/{container}/json'.format(container=name))
  File "/usr/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "./check_docker_multi", line 204, in get_url
    response = better_urllib_get.open(url, timeout=timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "./check_docker_multi", line 91, in socket_open
    return self.do_open(self.SocketFileToHttpConnectionAdaptor, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1208, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 380, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 342, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
UNKNOWN: Exception raised during check': timeout('timed out',)

**Comment by timdaman** [comment] 2018-03-24 02:31
Sorry for the delay replying. I find that error very surprising. Is there anything interesting about the box you ran that test on? Large number of containers? Very busy server?

Is this problem reproducible? Does it crash on the same line in `check_docker` (line 91 in the sample above) every-time?

The reason for my surprise is that the call it failed on is not the first time the API endpoint is hit. I wouldn't be surprised if the endpoint initially timed out but timing out later makes me suspect the endpoint (the docker sock file) might be flaky for some reason.

Given I am a bit at a loss could you let know  the version of OS and Docker you are running so I can try to set up a test environment.

**Comment by sadai-gh** [comment] 2018-03-27 14:11
I have good news, docker was indeed busy/hang because of some containers which have health checks and for some reason, I am currently not aware of, they get unhealthy, in this state you cannot get 'stats' or interact with this container anymore.
I assume with this version you search/query all containers for their names which means when a hung container is hit this causes the timeout?
Unless one container is unhealthy I can now monitor all of them bei their real name (which have more than one).
Unfortunately I don't know how to reproduce an unhealthy container but I think I should get rid of these checks, in non swarm mode they don't really have a function.

If you are interested what 'docker info' says:
Containers: 20
 Running: 20
 Paused: 0
 Stopped: 0
Images: 237
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 366
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-80-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 9.766GiB
Name: dock
ID: DJCA:MVGF:KQFW:42JO:KE4Q:4LRO:NHQY:E7FW:QSFY:5UQC:FBCS:X4JA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by timdaman** [comment] 2018-03-29 03:31
Thanks, that explains a lot. 

Indeed, with the new version I am looking at the list of names I get from the first call. Instead I am looking up the container by it's id to get it's `docker ps` display name and there is when I hit the timeout. It is rendering a lot of information so I will look at other ways to get this info or, at the very least, to give a more helpful response. 

I have a fairly busy week and weekend so it may be next week before I am able to do the R&D but you are welcome to use the branch until I have more solid solution worked out and merged.

As for health info, I still see that as useful, even without a swarm, as it gives more information for determining the root cause of an issue. For example a service that depends on another one (say a db) may decide instead of crashing, to go 'unhealthy' and keep trying.

**Comment by timdaman** [comment] 2018-03-29 03:46
I am curious. Looking at the same of names you sent as well as the following sample from my test env

`['/ccon/bar', '/name2', '/vigilant_darwin/bar']`

What I note from both of these example is only one of the names starts with a `/` and, in my example, that name matches the one I see in `docker ps`. Do you see that pattern holding on your systems? If so I think I have a easy hack around the timeout we are seeing as I don't have to do that extra lookup to get the name. 

That being said most checks one might chose to perform will eventually hit the call with the timeout so there is really no avoiding it so perhaps I should give up an improve the error handling.

**Comment by sadai-gh** [comment] 2018-04-06 08:18
First of all sorry for my late reply :(

I can confirm that the, lets call it, "real" name of the container only starts with / and has no second name which is the linked container.
So I think you could look for this scheme to identify the "real" one. I hope this helps you somehow.

**Comment by timdaman** [comment] 2018-04-15 17:56
FYI, I just pushed a release to resolve this problem. Look for version 2.0.5. It also should run faster too.

**Comment by timdaman** [comment] 2018-04-19 05:08
Closing this as I think the issue is resolved.

**Closed by timdaman** 2018-04-19 05:08 UTC
